// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: aisles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAisles = `-- name: CreateAisles :one
INSERT INTO aisles (id, name)
VALUES (
    encode(sha256(random()::text::bytea), hex), 
    $1
) 
RETURNING id, name
`

func (q *Queries) CreateAisles(ctx context.Context, name string) (Aisle, error) {
	row := q.db.QueryRowContext(ctx, createAisles, name)
	var i Aisle
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteAisles = `-- name: DeleteAisles :exec
DELETE FROM aisles
WHERE id=$1
`

func (q *Queries) DeleteAisles(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAisles, id)
	return err
}

const getAisles = `-- name: GetAisles :many
SELECT id, name FROM aisles WHERE id=$1
`

func (q *Queries) GetAisles(ctx context.Context, id uuid.UUID) ([]Aisle, error) {
	rows, err := q.db.QueryContext(ctx, getAisles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Aisle
	for rows.Next() {
		var i Aisle
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
