// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
)

type Aisle struct {
	ID   uuid.UUID
	Name string
}

type Item struct {
	ID          uuid.UUID
	Name        string
	Price       string
	NumberOf    int32
	Description string
	Location    uuid.NullUUID
}
